version: 2.1

orbs:
  allure: ayte/allure@0.1.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
    steps:
      - checkout

      - run:
          name: Run UI tests
          working_directory: "./ParleyPro Autotests"
          command: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Basics.xml

      - store_test_results:
          path: "./ParleyPro Autotests/target/allure-results"
          
      - run:
          name: Allure Report
          command: mvn allure:report
          when: always


workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master