version: 2.1

orbs:
  slack: circleci/slack@4.0.2
  allure: ayte/allure@0.1.3
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    steps:
      - checkout
      
      - run: 
          name: install Java
          command: |
            sudo apt update
            sudo apt install default-jre
            
      - allure/install
      
      - run: 
          name: Run Migration suite
          working_directory: "./ParleyPro Autotests"
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Migration.xml

      - run:
          name: Allure report generation
          working_directory: "./ParleyPro Autotests/target"
          command: allure generate --clean

      - store_artifacts:
          path: "ParleyPro Autotests/allure-report"
          destination: Report/Allure
          when: always
          
      - slack/notify:
          channel: qa
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": 
                  {
                    "type": "mrkdwn",
                    "text": ":warning: ParleyPro Autotests : *Failure* happened !"
                  }
                }
              ]
            }
          event: fail
          
            

workflows:
  commit:
    jobs:
      - build

  build_and_runTests:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build