version: 2.1

orbs:
  slack: circleci/slack@4.0.2
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    steps:
      - checkout
      
      - run:
          name: show info
          command: |
             uname -a ; echo 'Hello' ; java -version
          
      - slack/notify:
          channel: qa
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": 
                  {
                    "type": "mrkdwn",
                    "text": ":warning: ParleyPro Autotests : *Failure* happened !"
                  }
                }
              ]
            }
          event: fail
          
            

workflows:
  commit:
    jobs:
      - build

  build_and_runTests:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build