version: 2.1

parameters:
  env:
    type: string
    default: "" #possible values rc, prod
  tenantUrl:
    type: string
    default: "" #possible value like https://trackchanges.parleypro.net/master/index.html

orbs:
  slack: circleci/slack@4.0.2
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    steps:
      - checkout
      
      - run:
          name: Generate checksum file
          working_directory: "./ParleyPro Autotests"
          command: shasum pom.xml > checksum.tmp
          
      - restore_cache:
          working_directory: "./ParleyPro Autotests"
          key: m2z-{{ checksum "~/project/ParleyPro Autotests/checksum.tmp" }}

      - run:
          name: Define Environment Variable at Runtime
          command: |
            echo "export TENANT_URL=<< pipeline.parameters.tenantUrl >>" >> $BASH_ENV
            echo "export ENV=<< pipeline.parameters.env >>" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install Allure
          command: sudo curl -o allure-2.13.8.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz && sudo tar -zxvf allure-2.13.8.tgz -C /opt/ && sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure && allure --version
          
      - run:
          name: Update chromedriver
          command: cd; wget https://www.slimjet.com/chrome/download-chrome.php?file=files%2F86.0.4240.75%2Fgoogle-chrome-stable_current_amd64.deb; sudo apt install ./download-chrome.php\?file\=files%2F86.0.4240.75%2Fgoogle-chrome-stable_current_amd64.deb; sudo rm -f /usr/local/bin/chromedriver; wget https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip; unzip chromedriver_linux64.zip; sudo mv ./chromedriver /usr/local/bin/; chmod 775 `which chromedriver`; chromedriver -v; ls -la `which chromedriver`
      
      

      - run:
          name: Run Requests suite
          working_directory: "./ParleyPro Autotests"
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Requests.xml
          no_output_timeout: 20m

      

      - save_cache:
          key: m2z-{{ checksum "~/project/ParleyPro Autotests/checksum.tmp" }}
          paths:
            - "~/.m2"

      - run:
          name: Allure report generation
          working_directory: "./ParleyPro Autotests/target"
          command: sudo allure generate --clean

      - store_artifacts:
          path: "./ParleyPro Autotests/target/allure-report"
          destination: Report/Allure
          when: always

      - slack/notify:
          channel: qa
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text":
                  {
                    "type": "mrkdwn",
                    "text": ":warning: ParleyPro Autotests : *Failure* happened !"
                  }
                }
              ]
            }
          event: fail
          
            

workflows:
  commit:
    jobs:
      - build

  build_and_runTests:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build