version: 2.1
jobs:
  build:
    docker:
      - image: zenika/alpine-maven
    steps:
      - checkout

      - run:
          name: Run UI tests
          working_directory: "./ParleyPro Autotests"
          command: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Basics.xml

      - store_test_results:
          path: ./parley-tests/target/surefire-reports


workflows:
  build_and_run:
    jobs:
      - build:
          filters:
            branches:
              only: master