version: 2.1

orbs:
  slack: circleci/slack@4.0.2
  
jobs:
  runNumberedLists:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    steps:
      - checkout
      - run:
          name: Run Numbered lists suite
          working_directory: "./ParleyPro Autotests"
          command: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/java/suites/NumberedLists.xml
          
  runBasics:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    steps:
      - checkout
      - run:
          name: Run Basics suite
          working_directory: "./ParleyPro Autotests"
          command: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Basics.xml
          
  runApprovalWorkflow:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    steps:
      - checkout
      - run:
          name: Run ApprovalWorkflow suite
          working_directory: "./ParleyPro Autotests"
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/ApprovalWorkflow.xml
  
      
  uploadArtifacts:    
    - store_artifacts:
      path: "ParleyPro Autotests/allure-results.tar.gz"
          
    - store_artifacts:
      path: "ParleyPro Autotests/ScreenshotsOfFailedTests.tar.gz"
          
    - slack/notify:
        channel: qa
        custom: |
          {
            "blocks": [
              {
                "type": "section",
                "text": 
                {
                  "type": "mrkdwn",
                  "text": ":warning: ParleyPro Autotests : *Failure* happened !"
                }
              }
            ]
          }
        event: fail
          
            

workflows:
  commit:
    jobs:
      - runBasics
      - runApprovalWorkflow:
          requires:
            - runBasics

  runTests:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: master
    jobs:
      - runBasics
      - runApprovalWorkflow:
          requires:
            - runBasics
      