version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    working_directory: "./ParleyPro Autotests"
    steps:
      - checkout

      - run:
          name: Run UI tests
          command: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Basics.xml

      - run:
          name: ZIP allure results
          command: tar -czvf allure-results.tar.gz ./target/allure-results

      - store_artifacts:
          path: "ParleyPro Autotests/target/allure-results"
            

workflows:
  build_and_runTests:
    jobs:
      - build:
          filters:
            branches:
              only: master