version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
    steps:
      - checkout

      - run:
          name: Build project
          working_directory: ./parley-tests
          command: mvn clean install -U -DskipTests=true
      - run:
          name: Run IU tests
          working_directory: ./parley-tests
          command: mvn test -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver -Dsent.to.aws=true

      - store_test_results:
          path: ./parley-tests/target/surefire-reports


workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
