version: 2.1

orbs:
  slack: circleci/slack@4.0.2
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    working_directory: "./ParleyPro Autotests"  
      
    steps:
      - checkout
      
      - run:
          name: Run Numbered lists suite
          command: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/java/suites/NumberedLists.xml

      - run: sleep 10  

      - run:
          name: Run Basics suite
          command: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Basics.xml
          
      - run: sleep 10
          
      - run:
          name: Run ApprovalWorkflow suite
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/ApprovalWorkflow.xml
          
      - run: sleep 10
      
      - run: 
          name: Run ContractRoutingWorkflow suite
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/ContractRoutingWorkflow.xml
      
      - run: sleep 10
      
      - run:
          name: Run Classic suite
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Classic.xml
      
      - run: sleep 10
      
      - run:
          name: Run Formatting suite
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Formatting.xml
      
      - run: sleep 10
      
      - run:
          name: Run Templates suite
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Templates.xml
      
      - run: sleep 10
      
      - run:
          name: Run Regression suite
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Regression.xml

      - run: sleep 10
      
      - run: 
          name: Run Migration suite
          command: mvn test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Migration.xml

      - run:
          name: ZIP allure results
          command: tar -czvf allure-results.tar.gz ./target/allure-results

      - run: 
          name: ZIP Screenshots directory
          command: tar -czvf ScreenshotsOfFailedTests.tar.gz ./ScreenshotsOfFailedTests

      - store_artifacts:
          path: "ParleyPro Autotests/allure-results.tar.gz"
          
      - store_artifacts:
          path: "ParleyPro Autotests/ScreenshotsOfFailedTests.tar.gz"
          
      - slack/notify:
          channel: qa
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": 
                  {
                    "type": "mrkdwn",
                    "text": ":warning: ParleyPro Autotests : *Failure* happened !"
                  }
                }
              ]
            }
          event: fail
          
            

workflows:
  commit:
    jobs:
      - build

  build_and_runTests:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build