version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
      
    steps:
      - checkout

      - run:
          name: Run UI tests
          working_directory: "./ParleyPro Autotests"
          command: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/java/suites/Basics.xml

      - run:
          name: ZIP allure results
          working_directory: "./ParleyPro Autotests"
          command: tar -czvf allure-results.tar.gz ./target/allure-results

      - run: 
          name: ZIP Screenshots directory
          working_directory: "./ParleyPro Autotests"
          command: tar -czvf ScreenshotsOfFailedTests.tar.gz ./ScreenshotsOfFailedTests

      - store_artifacts:
          path: "ParleyPro Autotests/allure-results.tar.gz"
          
      - store_artifacts:
          path: "ParleyPro Autotests/ScreenshotsOfFailedTests.tar.gz"
            

workflows:
  build_and_runTests:
    jobs:
      - build:
          filters:
            branches:
              only: master